name: shop_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.0
  http: ^0.13.5
  shared_preferences: ^2.0.18
  flutter_lints: ^2.0.1


  cupertino_icons: ^1.0.5
  intro_screen_onboarding_flutter: ^1.0.0
  curved_navigation_bar: ^1.0.3
  clippy_flutter: ^2.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.1
  flutter_image_slideshow: ^0.1.5
  flutter_zoom_drawer: ^3.0.4+1
  carousel_slider: ^4.2.1
  dropdown_search: ^5.0.6
  intl_phone_field: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/product-placeholder.jpg
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/Capture.PNG
    - assets/images/profile.png
    - assets/images/images_slider/image1.jpg
    - assets/images/images_slider/image2.jpg
    - assets/images/images_slider/image3.jpg
    - assets/images/images_slider/image4.jpg
    - assets/images/profile_mask.png
    - assets/images/login_success.png

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
